language: python
python: 3.8

before_install:
  - sudo apt-get update
  - sudo apt-get install -y git unzip openjdk-8-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev

install:
  - pip install --upgrade pip virtualenv
  - pip install buildozer cython==0.29.19

script:
  - buildozer -v android debug
  - ls -la bin/

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: bin/*.apk
  skip_cleanup: true
  on:
    tags: true