[app]
title = FinanceApp
package.name = financeapp
package.domain = org.example
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 0.1
requirements = python3,kivy==2.3.0,cython==0.29.19
android.ndk_path = /home/runner/.buildozer/android/platform/android-ndk-r23b
android.sdk_path = /usr/lib/android-sdk
orientation = portrait
osx.python_version = 3
osx.kivy_version = 2.0.0
fullscreen = 0
android.api = 30
android.minapi = 21
android.ndk = 23b
android.sdk = 33
android.arch = armeabi-v7a
p4a.branch = master