name: Build APK
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y \
              git unzip openjdk-17-jdk \
              python3-pip python3-dev \
              libffi-dev libssl-dev zlib1g-dev \
              android-sdk-build-tools \
              android-sdk-platform-tools-common

      - name: Install Android SDK and NDK
        run: |
          mkdir -p ~/android-sdk
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools-linux-9477386_latest.zip -d ~/android-sdk/cmdline-tools
          mv ~/android-sdk/cmdline-tools/cmdline-tools ~/android-sdk/cmdline-tools/latest
          rm commandlinetools-linux-9477386_latest.zip
          
          yes | ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=~/android-sdk "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;25.2.9519653"
          
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$HOME/android-sdk/ndk/25.2.9519653" >> $GITHUB_ENV
          echo "PATH=$PATH:$HOME/android-sdk/platform-tools:$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_ENV

      - name: Install Buildozer and dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --no-cache-dir \
              buildozer \
              cython==0.29.36 \
              kivy==2.3.0 \
              "python-for-android==2024.1.21"  # Последняя стабильная версия

      - name: Configure Buildozer
        run: |
          # Create minimal buildozer.spec if missing
          if [ ! -f buildozer.spec ]; then
            echo "[app]" > buildozer.spec
            echo "title = FinanceApp" >> buildozer.spec
            echo "package.name = financeapp" >> buildozer.spec
            echo "package.domain = org.example" >> buildozer.spec
            echo "source.dir = ." >> buildozer.spec
            echo "version = 0.1" >> buildozer.spec
            echo "requirements = python3,kivy==2.3.0" >> buildozer.spec
            echo "" >> buildozer.spec
            echo "[android]" >> buildozer.spec
            echo "archs = armeabi-v7a" >> buildozer.spec
          fi
          
          # Update paths
          sed -i "s|^android.ndk_path = .*|android.ndk_path = $ANDROID_NDK_HOME|" buildozer.spec
          sed -i "s|^android.sdk_path = .*|android.sdk_path = $ANDROID_HOME|" buildozer.spec
          
          # Show final config
          cat buildozer.spec

      - name: Build APK
        run: |
          # Create required directories
          mkdir -p ~/.buildozer/android/platform
          mkdir -p .buildozer/android/platform/python-for-android
          
          # Build with debug info
          buildozer -v android clean
          buildozer -v android debug

      - name: Upload APK artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: bin/*.apk
          retention-days: 1