name: Build APK
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              git unzip openjdk-8-jdk \
              python3-pip python3-dev \
              libffi-dev libssl-dev zlib1g-dev \
              android-sdk-build-tools \
              android-sdk-platform-tools-common
          
          pip install --upgrade pip setuptools wheel
          pip install buildozer cython==0.29.19 kivy==2.3.0

      - name: Setup Android paths
        run: |
          echo "ANDROID_SDK_ROOT=/usr/lib/android-sdk" >> $GITHUB_ENV
          echo "PATH=$PATH:/usr/lib/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_ENV

      - name: Build APK
        run: |
          buildozer -v android clean
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: bin/*.apk
          retention-days: 1