name: Build APK
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              git unzip openjdk-11-jdk \
              python3-pip python3-dev \
              libffi-dev libssl-dev zlib1g-dev \
              build-essential autoconf libtool pkg-config \
              zlib1g-dev libncurses5-dev libncursesw5-dev \
              libtinfo5 cmake

      - name: Install Buildozer and dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install buildozer cython==0.29.36 kivy==2.3.0

      - name: Initialize Buildozer
        run: |
          # Создаем минимальный buildozer.spec
          echo "[app]" > buildozer.spec
          echo "title = FinanceApp" >> buildozer.spec
          echo "package.name = financeapp" >> buildozer.spec
          echo "package.domain = org.example" >> buildozer.spec
          echo "source.dir = ." >> buildozer.spec
          echo "version = 1.0" >> buildozer.spec
          echo "requirements = python3,kivy==2.3.0" >> buildozer.spec
          echo "" >> buildozer.spec
          echo "[android]" >> buildozer.spec
          echo "arch = armeabi-v7a" >> buildozer.spec

      - name: Build APK
        run: |
          buildozer -v android clean
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: financeapp
          path: bin/*.apk
          retention-days: 1