name: Build APK
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              git unzip openjdk-8-jdk \
              python3-pip python3-dev \
              libffi-dev libssl-dev zlib1g-dev \
              android-sdk-build-tools \
              android-sdk-platform-tools-common

      - name: Install Android NDK
        run: |
          mkdir -p ~/.buildozer/android/platform
          wget https://dl.google.com/android/repository/android-ndk-r23b-linux.zip
          unzip android-ndk-r23b-linux.zip -d ~/.buildozer/android/platform/
          rm android-ndk-r23b-linux.zip
          echo "ANDROID_NDK_HOME=$HOME/.buildozer/android/platform/android-ndk-r23b" >> $GITHUB_ENV

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install buildozer cython==0.29.19 kivy==2.3.0

      - name: Initialize Buildozer
        run: |
          buildozer init
          echo -e "\n[android]\nndk_path = $HOME/.buildozer/android/platform/android-ndk-r23b\nsdk_path = /usr/lib/android-sdk" >> buildozer.spec

      - name: Build APK
        run: |
          buildozer -v android clean
          buildozer -v android debug

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: bin/*.apk
          retention-days: 1