name: Build APK
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Install system dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y \
              git unzip openjdk-8-jdk \
              python3-pip python3-dev \
              libffi-dev libssl-dev zlib1g-dev \
              android-sdk-build-tools \
              android-sdk-platform-tools-common

      - name: Install Android NDK r25b
        run: |
          mkdir -p ~/.buildozer/android/platform
          wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip -q android-ndk-r25b-linux.zip -d ~/.buildozer/android/platform/
          rm android-ndk-r25b-linux.zip
          echo "NDK_PATH=$HOME/.buildozer/android/platform/android-ndk-r25b" >> $GITHUB_ENV

      - name: Install Buildozer and dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --no-cache-dir \
              buildozer \
              cython==0.29.36 \
              kivy==2.3.0

      - name: Initialize Buildozer
        run: |
          mkdir -p ~/.buildozer/android/platform/python-for-android
          buildozer init
          sed -i "s|# android.ndk_path = .*|android.ndk_path = $HOME/.buildozer/android/platform/android-ndk-r25b|" buildozer.spec
          sed -i "s|# android.sdk_path = .*|android.sdk_path = /usr/lib/android-sdk|" buildozer.spec
          sed -i "s|# p4a.branch = .*|p4a.branch = master|" buildozer.spec

      - name: Build APK
        run: |
          export BUILD_MEMORY=2048
          buildozer -v android clean
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: bin/*.apk
          retention-days: 1